### ISSUE TITLE
Error with get_state in download.py

### ISSUE THREAD

**Issue by JohnGiorgi** [jcpeterson/openwebtext#22]
Hi, I downloaded the pre-filtered URL list from [here](https://mega.nz/#F!EZZD0YwJ!9_PlEQzdMVLaNdKv_ICNVQ), and then tried to extract the text with `download.py` as per the readme

```bash
python download.py url_dumps_deduped/RS_2018-07.xz.deduped.txt \
    --n_procs 40 \
    --scraper bs4 \
    --chunk_size 100000 \
    --compress \
    --timeout 30
```

For plenty of `.txt` files, I face this error

```bash
Traceback (most recent call last):
  File "download.py", line 235, in <module>
    completed_uids, state_fp, prev_cid = get_state(month, args.output_dir)
  File "download.py", line 210, in get_state
    latest_cid = max([int(a.split("-")[-1].split("_")[0]) for a in archives])
ValueError: max() arg is an empty sequence
```

Is this a known error? I am planning to dig through the code to try and debug this but I first wanted to see if anyone else is facing this issue and knows the fix/cause

**Comment by vipulraheja** [comment]
Removing the file(s) in the `state` folder fixes the issue.
