### ISSUE TITLE
How to resume download after an error?

### ISSUE THREAD

**Issue by drfinkus** [jcpeterson/openwebtext#25]
Trying to restart a download after a failure (either due to a pycurl error, or a disconnect), throws an error:
When trying to resume, the script throws an error since the folder already exists. 
```
(base) user@desktop:/data/openwebtext$ python fetch_urls.py
Traceback (most recent call last):
  File "fetch_urls.py", line 39, in <module>
    main()
  File "fetch_urls.py", line 26, in main
    os.makedirs(OUTPUT_DIR)
  File "/home/user/miniconda3/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'pushshift_dumps_full'
```
This means I need to restart the download from the beginning. Is there a way to resume downloading? I already downloaded a large amount of data and I don't want to throw it away.

**Comment by drfinkus** [comment]
Nevermind. Resume functionality is built-in.
